### ISSUE TITLE
Author links wrong on `/blog` and `/`

### ISSUE THREAD

**Issue by tomayac** [GoogleChrome/web.dev#3680] opened 2020-08-11 08:09 UTC
The author links created [here](https://github.com/GoogleChrome/web.dev/blob/5c288789f55fd8110d383f20086df074c2a40994/src/site/_includes/components/AuthorsDate.js#L77) and [here ](https://github.com/GoogleChrome/web.dev/blob/5c288789f55fd8110d383f20086df074c2a40994/src/site/_includes/components/AuthorsDate.js#L47) are [dependent on whether an author has written articles or not](https://github.com/GoogleChrome/web.dev/blob/5c288789f55fd8110d383f20086df074c2a40994/src/site/_collections/authors.js#L47-L49). Since all authors with a Twitter profile on `/` and `/blog/` have links pointing to Twitter *despite having articles*, the check seems to not work as intended.

Una definitely does have articles. The author links on `/` point to her Twitter, though:

<img width="1044" alt="Screen Shot 2020-08-11 at 10 02 58" src="https://user-images.githubusercontent.com/145676/89872884-e378d100-dbb9-11ea-94bc-89036800be55.png">

The author links should consistently point to her author profile, as on `/content-visibility/`:

<img width="860" alt="Screen Shot 2020-08-11 at 10 07 25" src="https://user-images.githubusercontent.com/145676/89873390-a4974b00-dbba-11ea-9a1f-83370997e1a6.png">

**Comment by MichaelSolati** [comment] 2020-08-11 16:47
Duplicate of #3532

Though much better explained. I'll be working on it this week.

**Closed by MichaelSolati** 2020-08-11 16:47 UTC
Labels: bug
