### ISSUE TITLE
web.dev/promises flowchart 404's

### ISSUE THREAD

**Issue by TimvdLippe** [GoogleChrome/web.dev#2807] opened 2020-05-06 12:45 UTC
**Describe the bug**
The promises article includes a `promise-flow.svg` which 404's.

**To Reproduce**
1. Go to web.dev/promises
2. Open the console
3. See error

**Expected behavior**
Flow graph loads

```
promise-flow.svg:1 Failed to load resource: the server responded with a status of 404 ()
```

**Comment by robdodson** [comment] 2020-05-06 22:27
@kaycebasques did you migrate this one? temporarily assigning to you

**Comment by kaycebasques** [comment] 2020-05-07 01:49
@robdodson it's that error that we saw on the staging site. It works if you access it from `web.dev/promises/` but not `web.dev/promises`

**Comment by robdodson** [comment] 2020-05-07 02:26
This highlights an interesting bug which I think is caused by the service worker.

The svg is embedded using an iframe and a relative path, `<iframe src="promise-flow.svg">`. But if you visit the page without a trailing slash then that's like asking for `web.dev/promise-flow.svg` instead of `web.dev/promises/promise-flow.svg`.

**However**, this shouldn't be possible because our server should enforce trailing slashes. To prove this, open an incognito window and go to `https://web.dev/promises`. The svg should still load. Similarly, if you use the application panel to unregister the sw and set Bypass for network it'll load as expected when you visit /promises without the trailing slash.

We can fix this by changing the src on the iframe to `/promises/promise-flow.svg` but we should probably fix the underlying service worker issue as well.

**Comment by robdodson** [comment] 2020-05-07 02:26
I'll do a separate PR to update the iframe src, but I'm also tagging in Sam to see if he can look at the sw issue.

**Comment by samthor** [comment] 2020-05-07 05:02
Can I also point out that there's a bunch of iframes on this migrated page which should really have `loading="lazy"` set too? The Glitches, for example, load even when I open the page at the top and they're not visible yet :)

**Closed** 2020-05-08 03:40 UTC
Labels: bug

**Comment by kaycebasques** [comment] 2020-05-09 01:42
@samthor the top of our native lazy-loading post recommends not lazy-loading iframes: https://web.dev/native-lazy-loading/

**Comment by samthor** [comment] 2020-05-13 01:27
Right, that's not because it doesn't work, but rather that Chrome just has a possibly non-standard implementation. Thanks.
