### ISSUE TITLE
content: Declarative link capturing [2021-02-28]

### ISSUE THREAD

**Issue by kaycebasques** [GoogleChrome/web.dev#4725] opened 2021-02-24 17:38 UTC
* [Draft](https://github.com/WICG/sw-launch/blob/master/declarative_link_capturing.md)

**Comment by jpmedley** [comment] 2021-03-02 16:34
@mgiuca Can you please put your draft in a Google doc so that I can comment and make suggestions.

**Comment by mgiuca** [comment] 2021-03-03 03:37
Did you mean to move the explainer to a Google doc, or to write a new draft of a public blog post? (I think that explainer is not really formatted in a way that would make a good public post.)

I'm quite busy this week and I doubt I'll get time until next week at the earliest.

**Comment by jpmedley** [comment] 2021-03-03 16:53
>Did you mean to move the explainer to a Google doc, or to write a new draft of a public blog post?

I thought it was intended as a draft. The link on this side characterizes it that way.

>(I think that explainer is not really formatted in a way that would make a good public post.)

I was trying to figure out how to tell you that.

>I'm quite busy this week and I doubt I'll get time until next week at the earliest.

Please let me know.

**Comment by tomayac** [comment] 2021-03-16 16:03
Writing about this feature is on my plate. I went through the web.dev process and @kaycebasques has created this very Issue, but forgot to assign it to me. I just did that myself now.

@mgiuca, you're out of the loop and don't need to write anything, but I would appreciate a review once my article is ready (which is not yet the case due to a big annual Google event that is coming up).

**Comment by jpmedley** [comment] 2021-03-16 17:42
@mgiuca We hate to turn down any offer of help, but members of Dev Rel usually get first dibs on this stuff.

**Comment by mgiuca** [comment] 2021-03-17 00:55
Glad we've sorted it out!

**Closed** 2021-05-19 08:59 UTC
Labels: accepted, new content
