### ISSUE TITLE
Markdown reference links in `{% Aside %}` aren't recognized

### ISSUE THREAD

**Issue by petele** [GoogleChrome/web.dev#1617] opened 2019-10-08 16:55 UTC
**Describe the bug**
If I define a reference link (eg: `[my-link]: https://google.com`) at the bottom of my doc, then try to use it in an `{% Aside %}`, it doesn't recognize the reference link.

**To Reproduce**
1. At the bottom of your doc add `[my-link]: https://google.com`
2. In your main doc, add:

```
{% Aside %}
This is a test link to [Google][my-link], did it work?
{% endAside %}
```

**Expected behavior**
I would expect the link to be rendered.

**Actual behavior**
```
This is a test link to [Google][my-link], did it work?
```

**Comment by robdodson** [comment] 2019-10-09 16:51
I don't think this is an easy fix. If I recall, eleventy shortcodes don't have access to the entire doc, just the content you place inside of them. I realize it's a bit annoying, but I'd suggest not using reference links in Asides. I don't think this is something we'll have time to prioritize fixing so I'm going to recommend closing unless this is a blocker.

**Comment by petele** [comment] 2019-10-09 17:04
Can we keep this open for now, I'm fine with it not being fixed any time soon. We use reference links a lot in our docs and having this would be super helpful.

**Comment by robdodson** [comment] 2020-04-16 22:33
Keep this one open bot friend.

**Comment by robdodson** [comment] 2020-04-16 22:40
Btw I think this is caused by us parsing the markdown within the aside ourselves because we prefix the text with stuff like "Try it!".

We would either need to get rid of that prefixing or get rid of `{% Aside %}` altogether and switch over to something like what Sam Richard does for his site where they use emmet to do markdown expansion:

```
!!! .aside.aside--caution
This text gets wrapped in an aside
!!!
```

**Closed** 2021-03-11 20:37 UTC
Labels: accepted, bug
