### ISSUE TITLE
Bug when clicking the links to see more information.

### ISSUE THREAD

**Issue by konshensx16** [GoogleChrome/web.dev#728] opened 2019-03-15 07:39 UTC
**Welcome!** Please use this template for reporting documentation issues on https://web.dev

**Page Affected:** https://web.dev/measure

**What needs to be done?**

When getting the results for what could be fixed the url on the right of page are not properly constructed, see the image below, when i hover over the image i get {object object}
![Capture d’écran 2019-03-15 à 7 36 31 AM](https://user-images.githubusercontent.com/39305045/54415816-6069f780-46f5-11e9-99d8-8cadfff21c53.png)

Submitting this from work, have no time for proper usage, thank for an amazing tool by the way.

Cheers :)

**Comment by robdodson** [comment] 2019-03-18 23:05
We have a fix for this rolling out soon. Thanks for the report :)
Closing as a dupe of #724.

**Closed by robdodson** 2019-03-18 23:05 UTC
