### ISSUE TITLE
404 on Guides after audit

### ISSUE THREAD

**Issue by mercurial-hc** [GoogleChrome/web.dev#729] opened 2019-03-16 15:07 UTC
**Page Affected:** https://web.dev/measure

**What needs to be done?**
After running the audit, the suggested guide links which point to a page on web.dev/ are _404_'ed.
![Screenshot from 2019-03-16 20-34-31](https://user-images.githubusercontent.com/45140148/54477141-efc4f700-482a-11e9-8070-2e94dd55c274.png).
The navigation url in omnibar is probably erroneous and points to - .https://web.dev/[object%20Object] as shown in the screenshot below
![Screenshot from 2019-03-16 20-35-43](https://user-images.githubusercontent.com/45140148/54477159-20a52c00-482b-11e9-93c5-02507f9f10d1.png)

External links which point to guides on developers.google.com/ aren't affected.

**Comment by robdodson** [comment] 2019-03-16 17:57
Yeah :( we sent in a fix for this but are waiting on our infrastructure team to deploy it.

Closing as a dupe of https://github.com/GoogleChrome/web.dev/issues/724

**Closed by robdodson** 2019-03-16 17:57 UTC
