### ISSUE TITLE
{% Aside %} component breaks when nested in a numbered list

### ISSUE THREAD

**Issue by khempenius** [GoogleChrome/web.dev#4787] opened 2021-03-01 15:51 UTC
**Describe the bug**
Issues:
- All text within the `{% Aside %}` renders in "code-block" style - even if it is not a code block.
- The `{% Aside %}` breaks list numbering - the next list item after the `{% Aside %}` is always "1.".

**To Reproduce**
```
1. One

2. Two
  {% Aside %}
    Blah
  {% endAside %}

3. Three 
```

For more examples, see https://github.com/GoogleChrome/web.dev/pull/4764. This has a bunch of places where I used `**Note:**` or `**Optional**` headers to act as a defacto aside.

**Comment by jpmedley** [comment] 2021-03-08 16:42
I'm surprised we haven't. bumped into this before now. (maybe we're just now noticing.) Notes in procedures are a well-established idiom in technical writing.

**Comment by robdodson** [comment] 2021-03-08 20:54
I believe this is happening because the Aside on web.dev runs its own markdown parser so it doesn't have context about the outer list. I suspect if you use the Aside on developer.chrome.com it won't have this problem (it lets eleventy render the markdown ahead of time instead of rendering it itself).

We should bring the Aside from d.c.c. over to web.dev. Tentatively assigning to Ewa who is doing some feature parity work between the two sites.

**Comment by robdodson** [comment] 2021-03-11 19:53
We're doing some work in #4872 to improve the Aside but it doesn't look like it will solve this issue. I think the problem is that the Aside returns html and markdown-it just decides to close the list at that point and start a new one.

I think to work around this issue you could write the list using HTML since that's allowed in markdown.

```md
<ol>
  <li>One</li>
  <li>
    Two
    {% Aside %}
      An aside inside of an ordered list
    {% endAside %}
  </li>
  <li>Three</li>
</ol>
```

Would produce this:
![image](https://user-images.githubusercontent.com/1066253/110846112-43268000-8260-11eb-8294-2666b8b9d018.png)

@khempenius would that work for you? If so, is it ok for us to close this issue?

**Comment by robdodson** [comment] 2021-03-11 19:54
> All text within the {% Aside %} renders in "code-block" style - even if it is not a code block.

oh I forgot to mention I think we can fix this by disabling code block indention. We've always encouraged folks to use triple backticks so I think disabling this feature in markdown-it is good (we already disable it on developer.chrome.com).

**Comment by robdodson** [comment] 2021-03-11 19:55
oh it looks like we already globally disable it https://github.com/GoogleChrome/web.dev/blob/main/.eleventy.js#L145
and now that we're removing the markdown render from the Aside in #4872 it should be disabled there as well.

**Closed** 2021-03-11 20:37 UTC
Labels: bug
