### ISSUE TITLE
Images are not lazy-loaded without width and height attributes

### ISSUE THREAD

**Issue by iampava** [GoogleChrome/web.dev#4273] opened 2020-11-20 10:46 UTC
**Describe the bug**
The https://web.dev/browser-level-image-lazy-loading/ article mentions that although **width** and **height** attributes are recommended, they are not a requirement for lazy-loading.

![image](https://user-images.githubusercontent.com/11327761/99791447-4e796280-2b2e-11eb-8aa6-e034f324a5b5.png)

However, that doesn't seem to be the case. I removed those attributes from the demo here https://mathiasbynens.be/demo/img-loading-lazy and all images are loaded at once.

**To Reproduce**
1. Go to the demo page: https://mathiasbynens.be/demo/img-loading-lazy
2. Copy-paste HTML into a local file
3. Remove all width and height attributes
4. Open the page
5. Notice how all images are loaded at once

**Expected behavior**
Images should be lazy loaded

**Aditional Info**
Tested in Firefox Nightly(v85) and Chrome 86. Seems to behave similarly in both. So I assume lazy-loading doesn't work without sizes, in which case the article should be updated :)

**Comment by Malvoz** [comment] 2020-11-22 17:43
I reproduced this in Canary v89.0.4333.0 (from cold cache). Seemingly only the `height` attribute is required, if not present images are loaded eagerly. It does seem like a browser bug.

**Comment by iampava** [comment] 2020-12-23 08:00
Are we sure it's a bug? It reproduces in Firefox as well so my guess is that the docs need updated.

**Comment by spinweb1** [comment] 2021-01-14 22:52
I am experiencing this as well in Chrome.  If I remove the height and width attributes on img tags, all the images are loading at the outset.  For what it's worth, Edge is behaving the same way.  On Windows, only Firefox 84.0.2 is lazy loading images.

**Comment by robdodson** [comment] 2021-01-21 21:47
I'm not sure if this is a browser bug, or working as intended but perhaps not explicitly called out in the article so temporarily assigning to @housseindjirdeh till we can figure out next steps.

**Comment by spinweb1** [comment] 2021-01-22 16:13
Okay, thanks.  Because adding width and height attributes to the img tags affects responsive layouts, I'dreally hope it would work without them, but that's just my $0.02.

    On Thursday, January 21, 2021, 4:47:25 PM EST, Rob Dodson <notifications@github.com> wrote:  
 
 


I'm not sure if this is a browser bug, or working as intended but perhaps not explicitly called out in the article so temporarily assigning to @housseindjirdeh till we can figure out next steps.

**Comment by Malvoz** [comment] 2021-01-22 16:18
@spinweb1 

> Because adding width and height attributes to the img tags affects responsive layouts, I'dreally hope it would work without them

Even in a responsive layout you should be setting the intrinsic height and width of the image using the attributes, to avoid <span title="Content Layout Shift">CLS</span>. See https://developer.mozilla.org/en-US/docs/Web/Media/images/aspect_ratio_mapping for more information.

**Comment by spinweb1** [comment] 2021-02-13 23:03
@Malvoz Thanks.  I thought using height and width would break my responsive design, but that does not seem to be the case.

**Comment by NilsWiere** [comment] 2021-03-10 12:42
I’m also wondering whether this is a bug or intended to force people to prevent CLS. However, I still couldn’t find anything on that topic in the docs and for me it took some time to realize it doesn’t work at all without setting width and height attributes.

**Comment by domfarolino** [comment] 2021-04-10 17:12
I looked into this while debugging Chrome and I believe the issue is the website, not Chrome or Firefox lazyloading implementations. When you don't given an image a width or a height, it takes up no space. So if you stack 100 images on top of each other, before any of the images actually load (and thus produce a width or a height) all of the images are in-viewport because there is nothing pushing the later images beneath the viewport.

For example, if you remove the `width` and `height` attributes from the images and add an `<hr>` element in between each image, the `<hr>` element has a some non-zero computed height, and therefore even before some images load, the latter 40 or so images end up out-of-viewport and correctly load lazily.

The reason that the guidance in this article states that `width` and `height` are not necessary is because in the following HTML:

```html
<div height=100000px></div>
<img src=01.jpg loading=lazy>
<img src=02.jpg loading=lazy>
...
```

The above two images are clearly out-of-viewport, but shouldn't require `width` and `height` just to activate the `loading=lazy` state. However if you have a bunch of images that are in-viewport because nothing with height is pushing them out-of-viewport, then the internal lazy load IntersectionObserver correctly observes that all start in-viewport, and thus loads them.

So the more nuanced guidance should be: If an image appears out-of-viewport due to the structure of the page (text, other content, tall divs, etc), then you don't need `width` and `height` attributes. But if nothing on the page is pushing an `<img>` out-of-viewport, then it will be in-viewport of course. If you want to push lower images out-of-viewport with upper images, then the upper images, like any other content on a page, will need some non-zero height.

**Comment by robdodson** [comment] 2021-04-12 15:50
@housseindjirdeh @addyosmani @mathiasbynens would y'all have time to update the article with the out-of-viewport note?

**Comment by iampava** [comment] 2021-04-15 08:54
I created a PR in which added @domfarolino's explanation - https://github.com/GoogleChrome/web.dev/pull/5090. In case in helps to move things faster :D

**Closed** 2021-04-15 22:18 UTC
Labels: bug
