### ISSUE TITLE
content: Lighthouse 3 and 4 scoring - update wrong percentages

### ISSUE THREAD

**Issue by brucou** [GoogleChrome/web.dev#2406] opened 2020-03-22 17:47 UTC
### What page(s) need to be updated?
https://github.com/GoogleChrome/web.dev/blob/master/src/site/content/en/lighthouse-performance/performance-scoring/index.md#lighthouse-3-and-4

### Why is this update needed?
The sum of the percentages is 103% and seems to be a copy paste from Lighthouse 5 scoring percentages. This is probably due to a copy paste.

### What's the deadline?
Soon, it is easy stuff

#### Is it a hard deadline?
Nope. Importance is low. But it should be done to enable comparison of Lighthouse performance data over years (I have the case now from a benchmark which incorporates some Lighthouse data).

**Comment by kaycebasques** [comment] 2020-03-30 19:18
Duplicate of #2286

**Closed by kaycebasques** 2020-03-30 19:18 UTC
Labels: content, content update
