### ISSUE TITLE
Handbook lacks image information

### ISSUE THREAD

**Issue by jpmedley** [GoogleChrome/web.dev#2390] opened 2020-03-19 14:46 UTC
**Describe the bug**
The handbook's [Images and Video](https://web.dev/handbook/markup-media/) page contains no information about how much images should be compressed, and lists no tools with which to do the work.

**Comment by robdodson** [comment] 2020-03-19 15:08
cc @kaycebasques which tool have you been recommending?

I think since hero images go through our image CDN (which does compression for us) we probably want to go pretty light on compression, otherwise we'll end up with overly compressed images.

Images that are inside of posts currently do _not_ go through the image cdn, so it's helpful to compress those but I would like to get to a point where we're using the CDN for them as well.

Ultimately I'd like to get to a place where we're not checking images into the repo at all and instead providing a way for folks to upload them to a CDN or GCS bucket that we can pull from. But we're not there yet.

**Comment by robdodson** [comment] 2020-03-19 15:10
swapping the bug label for handbook and discussion. If it's ok, I'd like to reserve the bug label for anything related to the site displaying or working incorrectly.

**Comment by jpmedley** [comment] 2020-03-19 15:12
I didn't realize. Somebody asked me to compress an image the other day. That's why I thought it was an issue. They were asking for compression on our blog.

What's the timeline for getting the CDN to compress blog images?

**Comment by robdodson** [comment] 2020-03-19 15:18
> What's the timeline for getting the CDN to compress blog images?

Not sure. It would be a big change to the authoring experience and we need to think a bit about that.

**Comment by kaycebasques** [comment] 2020-04-30 01:07
Duplicate of #2030

**Closed by kaycebasques** 2020-04-30 01:07 UTC
Labels: content update, discussion, handbook
