### ISSUE TITLE
Add support for subcollections

### ISSUE THREAD

**Issue by jpmedley** [GoogleChrome/web.dev#1333] opened 2019-08-15 19:01 UTC
**Is your feature request related to a problem? Please describe.**
web.dev currently only supports two levels of content structure. While this is sufficient for most cases, a few content areas, such as PWAs for example, require more.

**Describe the solution you'd like**
The ability to support a third level of content structure.

**Describe alternatives you've considered**
skeletal pages that link to other first and second level content.

**Additional context**
Although four levels of content may be requested by some authors, such depth increases the likelihood of readers being lost with regards to the overall structure of a section. A need for a forth level can be better served by a more clever structuring of the content in the three levels. For these same reasons, a fifth level should not be considered at all.

**Comment by jpmedley** [comment] 2019-08-15 19:01
@petele

**Comment by petele** [comment] 2020-03-10 17:43
Actually closing as dupe of #1137

**Closed by petele** 2020-03-10 17:43 UTC
Labels: feature request
