### ISSUE TITLE
Move to using svg icons for all of web.dev

### ISSUE THREAD

**Issue by devnook** [GoogleChrome/web.dev#3309] opened 2020-06-22 14:11 UTC
We'd like to move to using svg icons for all of web.dev.  Especially if we inline the svg then the pages will render faster as we wont' have to wait for render blocking css or for the material font to be fetched.

We inherited the material icons font from devsite and never removed it. But now that LCP is becoming more important it's an optimization that we should make.

**Comment by robdodson** [comment] 2021-01-21 23:33
Dupe of #3809

**Closed by robdodson** 2021-01-21 23:33 UTC
Labels: accepted
