### ISSUE TITLE
content: TWA case study

### ISSUE THREAD

**Issue by kaycebasques** [GoogleChrome/web.dev#1576] opened 2019-09-27 01:43 UTC
**Author**: @petele 
**Reviewer**: TODO

**Target publish date:** 2019-10-28

- [ ] Check this box if this is a hard deadline.
- [ ] Check this box if you'd like your reviewer to fix grammar and punctuation issues for you.

**Process**

Check out the [web.dev writing process](https://web.dev/handbook/quick-start/).

When you're ready, make a copy of [this template](https://docs.google.com/document/d/1lgaNIEnXZf-RB8_p9RK22QEgpXJqnu77pLWVWVy4nuw/edit)
and fill in the proposal and outline sections. When you're finished, drop a link
to the doc in the 1st step below and check the box. A member of the web.dev team
will assign this ticket to themselves and work as your reviewer to help you
complete the remaining steps.

- [ ] 1. I've done my proposal <add a link to your proposal doc>
- [ ] 2. Proposal approved — _reviewer checks this_
- [ ] 3. I've added a draft to my proposal doc
- [ ] 4. Draft approved — _reviewer checks this_
- [ ] 5. I've submitted a pull request #<add PR number>
- [ ] 6. Pull request approved — _reviewer checks this_

**Comment by kaycebasques** [comment] 2019-09-27 16:26
I will mention you in a Google Doc comment. I kept the title generic here in order to not accidentally leak information.

**Comment by kaycebasques** [comment] 2019-09-27 17:06
Status: Pete wasn't aware of this content and said he doesn't have cycles for it. Thinks that Harleen or Aanchal put it on the tracker. I emailed Harleen & Aanchal asking for clarification and requesting them to find an author.

**Comment by carolrivero** [comment] 2019-10-16 09:10
This is a dupe of https://github.com/GoogleChrome/web.dev/issues/1682. @prash-mi submitted the issue. He's authoring this one.

**Closed** 2019-10-16 09:14 UTC
Labels: cds wave 2, content proposal, pwa
