### ISSUE TITLE
Undefined values for contributors

### ISSUE THREAD

**Issue by banadikt** [GoogleChrome/web.dev#5801] opened 2021-07-14 13:29 UTC
**Describe the bug**
In the "Conclusions and next steps" section of the "Learn CSS" course the people that help make this course have undefined values as their names.

**To Reproduce**
1. Go to 'Learn Section of web.dev'
2. Click on 'Learn CSS and then last section which is "Conclusions and next steps"'
3. Scroll down to 'Brought to you by'

**Expected behavior**
Have names of the contributors displayed instead of undefined values
![Screenshot 2021-07-14 at 14 23 43](https://user-images.githubusercontent.com/54352293/125630255-b7dfcad7-fe73-40eb-9d81-ae0c09634a64.png)

**Screenshots**

**Comment by tannerdolby** [comment] 2021-07-15 18:46
Duplicate of #5797 

One or the other should be closed and the conversation consolidated to a single issue.

**Comment by MichaelSolati** [comment] 2021-07-16 22:04
@banadikt thank you for reporting this, though we've been made aware of this and a fix is coming soon. We will continue to track it with issue #5818 .

**Closed by MichaelSolati** 2021-07-16 22:04 UTC
Labels: P2, bug
