### ISSUE TITLE
"Fav Kitties" Glitch project used in https://web.dev/minify-css/#measure is suspended

### ISSUE THREAD

**Issue by beaufortfrancois** [GoogleChrome/web.dev#2341] opened 2020-03-11 09:52 UTC
**Describe the bug**
"Fav Kitties" Glitch project used in https://web.dev/minify-css/#measure is suspended

**To Reproduce**
1. Go to https://web.dev/minify-css/#measure
2. Click on 'Fav Kitties' link

**Expected behavior**
Use should be able to run audit for https://fav-kitties-animated.glitch.me
Sadly this page returns a glitch error page that says "Project fav-kitties-animated suspended: Error while preparing the project. Please contact Glitch Support."

**Screenshots**
![image](https://user-images.githubusercontent.com/634478/76404119-430e4e80-6386-11ea-8205-d58ed4427778.png)

@Meggin seems to be the owner of this project.

**Comment by robdodson** [comment] 2020-03-11 23:19
bummer. @housseindjirdeh are you able to take a look at this one?

**Comment by housseindjirdeh** [comment] 2020-03-12 13:44
:(

It might be going over-cap on disk space limits. Will take a look today or next week at the latest 🚀

**Comment by beaufortfrancois** [comment] 2020-03-16 07:34
For info, I've contacted Glitch support as well at https://support.glitch.com/t/project-fav-kitties-animated-suspended/20403

**Comment by beaufortfrancois** [comment] 2020-03-17 15:57
Glitch support team came back with message below:

> This error happened because the project was quickly approaching the  disk space limit.
> 
> To help, I gave the project some extra disk space for the next 24 hours.  During this time, the project members should go into the project and remove any unnecessary files to save space. If this is not done within 24 hours, the project will be automatically suspended again.
> 
> If you are a project member that is able to edit the project and need tips on how to reduce the disk space being used, let me know!

@housseindjirdeh @Meggin @demianrenzulli Please accept my request to join project so that we can clean this project.

**Comment by demianrenzulli** [comment] 2020-03-17 16:13
Thank you for flagging this. Just gave access to @beaufortfrancois.

Francoise, please, let me know if you need anything else.

**Comment by beaufortfrancois** [comment] 2020-03-17 19:59
187MB are used. by the project. @housseindjirdeh Can you clean it properly?

**Comment by robdodson** [comment] 2020-03-17 21:17
I wasn't able to get the app to start (I bet Glitch is under a lot of load these days). But I was wondering—what's actually using all the space?

**Comment by demianrenzulli** [comment] 2020-03-17 21:47
Hi @robdodson, according to @beaufortfrancois this is due to the node_modules folder. I'm wondering if it's only affecting this version of Fav Kitties (perhaps for having ran some commands manually in the console), or all of them?

**Comment by beaufortfrancois** [comment] 2020-03-18 06:42
I was wrong. According to https://glitch.com/help/restrictions/, it seems like node_modules don't count  towards that limit of 200MB. I've asked Glitch support folks for more help.

**Comment by beaufortfrancois** [comment] 2020-03-18 07:08
I've just ran `git gc --aggressive` and disk usage went from 178MB to 36MB.
Hopefully we should be good now ;)

![image](https://user-images.githubusercontent.com/634478/76934512-91c06900-68ef-11ea-8e1b-c86e0b8902a5.png)

**Comment by beaufortfrancois** [comment] 2020-03-18 07:11
I'll let you know when I hear from Glitch support folks.

**Comment by demianrenzulli** [comment] 2020-03-18 15:19
Thanks for going the extra mile on this @beaufortfrancois. Good to see the issue is more clear now.

Please, let us know if we can help.

**Comment by robdodson** [comment] 2020-03-18 15:47
yes thank you @beaufortfrancois, we really appreciate it :)

**Comment by beaufortfrancois** [comment] 2020-03-18 19:32
Glitch folks came back:

> Looks good!  I voted for Whiskers. ^..^

I think we can close this issue.

**Comment by robdodson** [comment] 2020-03-18 19:59
ok, thank you @beaufortfrancois :)

I'm curious if we will need to periodically run `git gc --aggressive` in the future. I guess we can see if this issue pops up again and if so we'll explore if we need to do any ongoing actions. For now I'm +1 on closing.

**Comment by robdodson** [comment] 2020-04-17 00:26
This seems to be happening for other glitches so I started a support thread.
https://support.glitch.com/t/suspended-project-error-while-preparing-project/22154/6

**Comment by robdodson** [comment] 2020-05-16 15:49
I think Houssein was able to fix these a while back. Going to close but happen to reopen if we hit issues again.

**Closed by robdodson** 2020-05-16 15:49 UTC
Labels: bug
