### ISSUE TITLE
content: Loading third-party resources effectively

### ISSUE THREAD

**Issue by Meggin** [GoogleChrome/web.dev#672] opened 2019-03-01 23:45 UTC
This covers how to load third-party resources effectively.

We will need to work out overlap with similar docs in /web and make sure we have a migration strategy.

For example, this guide has overlap: https://developers.google.com/web/fundamentals/performance/optimizing-content-efficiency/loading-third-party-javascript/

**Comment by addyosmani** [comment] 2019-03-19 15:47
Let's work on this after #665

**Comment by Meggin** [comment] 2019-04-09 21:41
Will this guide cover some strategies for eliminating render blocking resources?

**Comment by Meggin** [comment] 2019-04-25 17:30
@addyosmani, I know this is next on the list for Fast guides, but fairly sure it won't make it in for v1. OK for me to de-scope?

**Comment by mihajlija** [comment] 2019-04-25 19:51
I can confirm that de-scoping is okay 👍  I'm working on it, but I have 4 other doc reviews in progress and I won't be available next week (Orthodox Easter and Labour Day are national holidays over here).

**Comment by Meggin** [comment] 2019-06-01 00:21
Changing labels post-Google IO. Keeping it open though, as I presume we still want this content.

**Comment by mfriesenhahn** [comment] 2019-07-10 15:20
Closing issue since it no longer aligns to a single post.

**Closed by mfriesenhahn** 2019-07-10 15:20 UTC
Labels: content proposal, dgc-migration, fast, p1
