### ISSUE TITLE
Possible minor issue in the last illustration of the "Learn CSS" course chapter 12 about spacing

### ISSUE THREAD

**Issue by remigius42** [GoogleChrome/web.dev#5630] opened 2021-06-15 10:07 UTC
**Describe the bug**
There might be a small issue with the last illustration of [chapter 12 in the "Learn CSS" course](https://web.dev/learn/css/spacing/): the vertical gaps between text segments are all indicated to be `1 em` wide, however the third one is considerably wider than the other three (Inkscape indicates 26 pixels in height vs. 16 pixels for the other three gaps).
A PNG export of the SVG illustration is shown in the screenshots below as well as the proposed fix right next to it. Because SVGs cannot be uploaded directly, the fix also attached as a [Zip file 8eun6aGNHPTr4kyOrYkc_gap_fixed.svg.zip](https://github.com/GoogleChrome/web.dev/files/6654665/8eun6aGNHPTr4kyOrYkc_gap_fixed.svg.zip).
Based on the file name and the fact that I did not find anything in the repository, I assume, that content specific media assets are managed via an internal CMS, otherwise I would have opened a pull request directly, as it was the case for pull request #5619 of the bug ticket #5618.

**To Reproduce**
1. Go to the [last section of chapter 12 in the "Learn CSS" course](https://web.dev/learn/css/spacing/#creating-consistent-spacing)
2. Compare the gaps between the text segments in the illustration, which are all supposed to be equal (`1 em`).

**Expected behavior**
The gaps between the text segments should be identical.

**Screenshots**
| original | proposed fix |
| --- | --- |
| ![8eun6aGNHPTr4kyOrYkc](https://user-images.githubusercontent.com/4507564/122033347-b9430180-cdd0-11eb-8170-0b41843d74f3.png) | ![8eun6aGNHPTr4kyOrYkc_gap_fixed](https://user-images.githubusercontent.com/4507564/122033476-d7106680-cdd0-11eb-92b9-1921bd5550fb.png) |

**Comment by una** [comment] 2021-06-15 20:22
Dupe of #5618

**Comment by remigius42** [comment] 2021-06-16 08:06
Dear @una, thank you for looking into this as well as for the course and the podcast. Personally, I would not consider this a duplicate in the sense that I created #5618 and this ticket as separate tickets on purpose, because for #5618 I can provide a suggested fix in terms of a pull request (#5619), whereas for this issue, I think I won't be able to do so, if my assumption regarding the CMS [stated above is correct](https://github.com/GoogleChrome/web.dev/issues/5630#issue-921230995). I merely [mentioned it](https://github.com/GoogleChrome/web.dev/pull/5619#issuecomment-861420349) within #5619, because I saw that @argyleink had been assigned to #5618 and figured it might facilitate the resolution of both tickets. Still, you are of course correct that judging by the title of #5618, this issue could be considered a part of the minor issues as well and in any case, neither am I familiar with the usual ticket handling within this project nor do I want to complicate things unnecessarily.

Based on the conversation on #5539 my current workflow looks as follows

1. If I see something which might be an issue, if possible, I fix it on my fork of the repository on a dedicated branch.
2. Then I open a ticket with the `bug label` in order to get an issue key. If I assume that I cannot provide a pull request, steps 3 and 4 will be omitted, as it was the case for this ticket.
3. I amend all commits on the bugfix branch with the issue key of the previously opened ticket and add a `Fixes` Git commit message trailer to the last commit, such that the associated ticket is closed upon merge.
4. I open the pull request which will automatically be associated with the ticket due to the issue key references.

The reasons for this sequence are, that I would like to prevent unnecessary efforts, by keeping the time between opening the ticket and the pull request short, such that it is clear, that if the bug was confirmed, there might already be a fix for it. Additionally, I open both a ticket and a pull request, because from my perspective, they are semantically different and one ticket might reference multiple pull requests, while the opposite should be rare.

Currently, I am trying to find a balance between ticket independence (to prevent duplicates and overlap) and ticket overhead, which is why I batched the commits of #5619 into one ticket, because the three commits would otherwise have ended up in three tickets and three pull requests. If anyone involved in this course or this repository in general would prefer a different workflow, I will of course be happy to change it, especially because I think it is unlikely, that for the minor corrections, there will be more than one pull request per ticket and as such simply opening a pull request (if there is a code-based fix) without an additional ticket might reduce the overhead significantly.

**Comment by devnook** [comment] 2021-06-16 13:27
Hi @remigius42, thanks for caring about Learn CSS content!

I think the picture you describe is actually correct. 1em is a relative measure and refers to "current font size" of the element. This is why for a paragraph it is small, and for the header it is wider. Compare it with this codepen:

https://codepen.io/devnook/pen/OJpdXev

You can read more about it here: https://web.dev/learn/css/sizing/

**Closed by devnook** 2021-06-16 13:27 UTC
Labels: bug, content

**Comment by remigius42** [comment] 2021-06-16 14:03
Dear @devnook, thank you for your explanation and the CodePen 👍!
