### ISSUE TITLE
Cards in blog sections are interactive but doesn't work when clicked in whitespaces 

### ISSUE THREAD

**Issue by vikas-parashar** [GoogleChrome/web.dev#4794] opened 2021-03-02 14:31 UTC
**Describe the bug**
Card in blog sections are not entirely clickable while there is visual feedback for the click.

**To Reproduce**
1. Go to https://web.dev/blog/
2. Click on any card but in whitespace
4. Clicking should take to the article but nothing happens while providing visual cues that card can be clicked anywhere.

**Expected behavior**
Clicking anywhere on the card should take to the article.

**Screenshots**
https://user-images.githubusercontent.com/5694967/109661816-489a1100-7b62-11eb-8fd9-0ecb56b03c5c.mov

**Comment by robdodson** [comment] 2021-03-23 20:14
I think we are going to consider this a feature and not a bug. @MarianaPicolo worked on a fix for this, but when we reviewed it with the team we discovered that some teammates currently rely on selecting text in the card and using text-to-speech to reach the content. They do this by first clicking in the non-interactive whitespace and dragging the text selection. Since this seems like an important accessibility use case we want to preserve the functionality.

**Closed by robdodson** 2021-03-23 20:14 UTC
Labels: bug
