### ISSUE TITLE
content: Storage Foundation API (née Native I/O) [2021-02-28]

### ISSUE THREAD

**Issue by kaycebasques** [GoogleChrome/web.dev#4487] opened 2021-01-20 03:50 UTC
* [thread](https://groups.google.com/a/google.com/g/webdev-content/c/U2JlolE8pWI)
* draft: TBD

**Comment by niieani** [comment] 2021-02-10 03:11
Hey @kaycebasques, I'm seeing "Content unavailable" when opening up the linked thread. Is is access-gated?

**Comment by tomayac** [comment] 2021-02-10 11:17
> Hey @kaycebasques, I'm seeing "Content unavailable" when opening up the linked thread. Is is access-gated?

This is an internal group thread, yes. It basically just contains the proposal for the article. The PR will be public, so you can have a look at the staged content once work starts on this.

**Comment by tomayac** [comment] 2021-03-15 15:45
Active

**Comment by tomayac** [comment] 2021-03-17 11:34
*"The Storage Foundation API gives developers a performant and direct storage option akin to a basic file system to build higher-level abstractions like databases or manage large temporary files."*

**Comment by robdodson** [comment] 2021-06-07 15:41
@tomayac it looks like this issue has been open since January. If there are aren't immediate plans to write about it I'd like to ask that we close the ticket to reduce noise on the issue tracker. The `accepted` label is really only supposed to be used by the engineering team to indicate threads that we're planning to work on in a coming sprint.

But I'd like to understand what value y'all get from leaving the ticket open? Are you worried that if the ticket is closed that you'll lose track of the post? I'd like to find a solution that doesn't disrupt y'alls workflow but also doesn't leave stale tickets in the project.

**Comment by tomayac** [comment] 2021-06-07 15:50
Work on this is happening in https://github.com/GoogleChrome/web.dev/pull/5559.

An Issue in `open` state means I have to work on it and _will_ eventually. In Fugu land, priorities shift, so we may think something needs attention and file the web.dev request, but then something else may come up or the feature may be delayed. The auto-closing of the Issue is super annoying in this context, which is why the `accepted` label comes in so handy. If there's a better way to exclude Issues from the bot, I'd happily take it.

**Comment by robdodson** [comment] 2021-06-08 22:23
For a bit of context, we originally added the stalebot because folks were opening issues and PRs for content but then abandoning them, or they would stall for months, and it made it hard for our team to track how we were doing managing our overall issue count. It also meant our teammates were periodically having to check-in on issues to see if they were still valid or should be closed.

So I think it's a little annoying for both sides: It's annoying for you because you have to keep fighting off the bot, and it's annoying for us because folks in the past have used the tracker as a place to braindump without bothering to clean up after themselves.

I think one thing we could do is really increase the timeout on the stalebot so it goes from 30 days to 90 days before it pings the ticket, that way folks have essentially an entire quarter to work on something, and if they haven't gotten to it by then, then maybe it really is stale.

**Comment by tomayac** [comment] 2021-06-09 04:54
Increasing the timeout sounds like a great compromise! Thanks, @robdodson!

**Closed** 2021-06-16 08:19 UTC
Labels: accepted, new content
