### ISSUE TITLE
Closing the detailed description of a day 2 or 3 web.dev/live talk resets the tabbed list to day 1

### ISSUE THREAD

**Issue by TimvdLippe** [GoogleChrome/web.dev#3390] opened 2020-06-26 23:22 UTC
**Describe the bug**
When clicking on the detailed description of a talk on either day 2 or day 3 of web.dev/live, after closing the dialog, the tabbed list resets to day 1.

**To Reproduce**
1. Go to web.dev/live
2. Click on Day 3
3. Click on a talk
4. Click close
5. Observe that the schedule is reset to day 1

**Expected behavior**
It should stay on day 3 after closing the modal.

**Screenshots**

**Comment by robdodson** [comment] 2020-06-27 00:42
Thanks for flagging this. I think it's a dupe of #3336. Glad you could confirm it was happening for you as well. I'll see if I can fix this.

**Closed by robdodson** 2020-06-27 00:42 UTC
Labels: bug
