### ISSUE TITLE
Handbook pages are missing

### ISSUE THREAD

**Issue by jpmedley** [GoogleChrome/web.dev#3487] opened 2020-07-13 14:43 UTC
**Describe the bug**
The landing page for the handbook is present, but the links to return 404.

**To Reproduce**
1. Go to the [handbook landing page](https://web.dev/handbook/).
2. Click any of the links.

I did not test all of them. The 4 or 5 I did test all return 404.

**Comment by kaycebasques** [comment] 2020-07-13 17:33
Duplicate of #3473 

FYI @jpmedley you can still manually access them by adding `/handbook/` to the URLs. E.g. the first link on `https://web.dev/handbook` is `https://web.dev/quick-start` (which 404s) but you can access the page at `https://web.dev/handbook/quick-start`

**Closed by kaycebasques** 2020-07-13 17:33 UTC
Labels: bug, p0
