### ISSUE TITLE
Scheduled blog post doesn't result in updated index after go-live

### ISSUE THREAD

**Issue by jeffposnick** [GoogleChrome/web.dev#2908] opened 2020-05-18 14:39 UTC
**Describe the bug**
A scheduled /blog post has gone live, but the https://web.dev/blog/ page isn't updated to include it.

**To Reproduce**
1. https://github.com/GoogleChrome/web.dev/pull/2875 was merged last week, with a scheduled go-live date of May 18.
2. The post is live at https://web.dev/appcache-removal/
3. If you visit https://web.dev/blog/, it's not listed there. The most recent post is currently from May 12.
4. This is reproducible via a Chrome Incognito window as well, i.e. without service worker involvement. The full HTML response for https://web.dev/blog/ retrieved directly from the server doesn't contain the new blog post either.

**Expected behavior**
The https://web.dev/appcache-removal/ post should be listed at https://web.dev/blog/

If I check out a local copy of web.dev from GitHub and run `npm run build && npm run start` against the master branch, I see the expected post in the /blog index.

**Screenshots**
<img width="1454" alt="Screen Shot 2020-05-18 at 10 37 18 AM" src="https://user-images.githubusercontent.com/1749548/82225776-9e633c80-98f3-11ea-9c13-e912dd35f97d.png">

**Comment by jpmedley** [comment] 2020-05-18 14:40
I noticed while poking around in DevTools that the blog page has an earlier time stamp than the article. Mon May 18 2020 07:22:19 GMT-0700 (Pacific Daylight Time) for the article and Mon May 18 2020 07:15:51 GMT-0700 (Pacific Daylight Time) for the blog page. I copied the high res time stamps from Application tab and converted them in the console.

**Comment by jeffposnick** [comment] 2020-05-18 16:12
...and this has now fixed itself, as https://web.dev/blog/ includes the expected link to https://web.dev/appcache-removal/.

Feel free to close this issue if it was just a case of needing to wait until X o'clock on the given day for some automatic process to take place.

**Comment by jpmedley** [comment] 2020-05-18 16:20
I'd prefer to leave this open until we know for sure. If that's what it was, I'll make this ticket about documenting it in the handbook.

**Comment by robdodson** [comment] 2020-05-18 16:49
I think this may be working as intended. When you looked at the live post did you scroll down to see if it had a "This post is a draft" banner?

When something is merged it creates a file in dist and gets deployed with the site. This includes anything with `draft: true` (a scheduled post just sets `draft: true` until the right date). These posts are hidden from search and display a banner indicating that they're drafts. They won't appear on the /blog/ page or anything.

The post should truly go live when the site does its daily automatic build at 15:00 UTC time.

**Comment by robdodson** [comment] 2020-05-18 16:50
Related issue: https://github.com/GoogleChrome/web.dev/issues/2716

**Comment by jeffposnick** [comment] 2020-05-18 17:05
I can't be 100% sure right now, but no, I don't *remember* seeing a "This post is a draft" banner when I checked this morning.

But it sounds like it's the automatic build at 15:00 UTC time that resolved the issue, so feel free to repurpose this issue to track getting the handbook updated (if it's not mentioned there already).

**Comment by robdodson** [comment] 2020-05-18 17:28
yeah it's sorta mentioned. https://web.dev/handbook/markup-post-codelab/#set-up-the-yaml
scheduled is explained but the weird draft stuff isn't. I'd like to see if I can just make eleventy not output the file since it causes so much weirdness.

**Comment by tomayac** [comment] 2020-05-18 19:42
The /idle-detection/ post still doesn't show :-( It wasn't scheduled, just a regular merge and wait for the deploy publish.

**Comment by tomayac** [comment] 2020-05-19 10:24
Just made a quick [edit](https://github.com/GoogleChrome/web.dev/pull/2917), maybe this triggers a rebuild for the [page](https://web.dev/idle-detection/) to be listed on [/blog](https://web.dev/blog/).

**Comment by jeffposnick** [comment] 2020-05-19 14:27
Oh! So @tomayac, you need to use the tag `blog` now, not `post`. Otherwise it won't be listed on `/blog`.

I think they made this change within the past couple of weeks.

**Comment by tomayac** [comment] 2020-05-19 15:08
🤦‍♂️ Opened https://github.com/GoogleChrome/web.dev/pull/2919

Thanks for the eagle eye, @jeffposnick.

**Comment by robdodson** [comment] 2020-05-19 18:01
I'm going to close this issue and we can revist the next time we experiment with a scheduled post.

**Closed by robdodson** 2020-05-19 18:01 UTC
Labels: bug
