### ISSUE TITLE
content: TODO

### ISSUE THREAD

**Issue by beussery** [GoogleChrome/web.dev#3903] opened 2020-09-17 16:57 UTC
Wording "Initial server response time was short" appears when response time is actually too long.  Should say "Initial server response time was too long" or similar.

https://web.dev/measure/

It links to https://web.dev/time-to-first-byte/

### What's the deadline?
When possible

#### Is it a hard deadline?
no

If yes, please explain why.

**Comment by robdodson** [comment] 2020-09-23 22:47
Dupe of #3888

**Closed by robdodson** 2020-09-23 22:47 UTC
Labels: content update
