### ISSUE TITLE
Pages are missing their meta description.

### ISSUE THREAD

**Issue by kaycebasques** [GoogleChrome/web.dev#3632] opened 2020-08-05 00:57 UTC
Just noticed that the `description` field that we've provided for https://web.dev/read-files isn't being used by Google Search. I'm creating this issue to remind myself to investigate further and see if it's happening on other pages.

![image](https://user-images.githubusercontent.com/4713486/89359955-e6386b00-d67b-11ea-8a36-d9e2707ebf93.png)

**Comment by robdodson** [comment] 2020-08-10 23:00
It looks like there's no meta description tag on that, or any other blog post page. Seems like a big bug.

**Comment by robdodson** [comment] 2020-08-10 23:07
Doing some digging. If I do `ELEVENTY_ENV=prod npm run build` it generates pages with a meta description. But if I view the live pages in incognito the description isn't there. So somewhere along the way it's getting stripped out.

**Comment by robdodson** [comment] 2020-08-10 23:38
Seems like this is caused by the service worker. If you cmd-shift-r refresh the page and look in devtools you'll see that it has a meta description. If you then do a cmd-r refresh the meta description goes away.

**Comment by robdodson** [comment] 2020-08-10 23:39
Tentatively assigning to @samthor to take a look at

**Comment by robdodson** [comment] 2020-08-18 02:32
Bumping this up to p0 as it seems to be negatively impacting our search rankings and probably our analytics.

**Comment by robdodson** [comment] 2020-08-18 02:39
I'm having a hard time figuring out if this is something going wrong on our end or if Search is just indexing our pages weirdly.

Here's some steps:
- Google "web.dev catalina" expecting to find [this article](https://web.dev/more-variable-font-options-in-chromium-83/)
- Scroll down looking for search results

**Expected (taken from metatags.io)**
![image](https://user-images.githubusercontent.com/1066253/90464059-57870d80-e0c1-11ea-996a-7955845aa04a.png)

**Actual**
![image](https://user-images.githubusercontent.com/1066253/90464093-64a3fc80-e0c1-11ea-9d67-c5716a79fa86.png)

**Comment by robdodson** [comment] 2020-08-18 02:41
Search Console is showing the page as being in the index, and if you look at the crawled page on the right, it seems to have its meta description:

![image](https://user-images.githubusercontent.com/1066253/90464194-9fa63000-e0c1-11ea-8fc7-94f6746291dd.png)

**Comment by robdodson** [comment] 2020-08-18 02:57
Related, it looks like our sitemap is totally broken:
![image](https://user-images.githubusercontent.com/1066253/90465220-c5cccf80-e0c3-11ea-85fd-cfe643995373.png)

The url's are just /foo/ but they need to be "https://web.dev/foo/" to be valid. I'll send in a PR.

**Comment by robdodson** [comment] 2020-08-18 03:01
Moving this back to p1 because I still can't tell if we even have an issue...

**Comment by robdodson** [comment] 2020-08-18 03:17
Hm I think maybe something is going on with our setup.

- In a new incognito window, Google 'same site cookies'
- Rowan's article is the first link, click on it.
- Open the devtools and inspect the <head>

**Expected behavior**
There's a meta description in the head

**Actual behavior**
There's no meta description in the head

Maybe the router is failing to add it? 🤷‍♂️

**Comment by samthor** [comment] 2020-08-18 03:20
You're probably seeing the SW response by that point, which doesn't include
headers.

You pretty much always want to test like this:

$ curl https://web.dev/samesite-cookies-explained/ | head -n 40

Or by toggling cache/network settings in devtools.

**Comment by robdodson** [comment] 2020-08-18 03:20
yeah I deleted my comment as I realized my incognito may have been tainted by a prior sw

**Comment by robdodson** [comment] 2020-08-18 03:21
So the description is there but it's definitely not showing up in search results. Oddly the thing that is showing up in search results is several paragraphs in. I'm hecka confused.

**Comment by kaycebasques** [comment] 2020-08-18 03:55
Perhaps Search just treats the description as a suggestion, rather than a guarantee? I.e. Search uses its own logic to decide what to post under the title…

**Comment by robdodson** [comment] 2020-08-18 06:01
Yeah I guess so. Maybe we can ask Martin to help us confirm tomorrow.

Looking at the analytics I'm thinking/hoping that the drop-off has more to do with Harleen ending some ad campaigns and not our results getting dropped

**Comment by robdodson** [comment] 2020-08-18 15:57
Martin pointed me at this article: https://support.google.com/webmasters/answer/35624?hl=en

It sounds like search may choose to use a different title and description if it thinks it's found one that's more relevant.

**Comment by robdodson** [comment] 2020-08-19 22:00
Removing the p1 label as I _think_ things are working as intended

**Closed by robdodson** 2020-08-19 22:00 UTC
Labels: bug
