### ISSUE TITLE
FileSystemAPI not working with Html5 drag & drop

### ISSUE THREAD

**Issue by pradeeptakhatoi** [GoogleChrome/web.dev#5907] opened 2021-08-02 04:22 UTC
**Describe the bug**
While clicking on a button I am calling **showDirectoryPicker** function of the FileSystemAPI

` const dirHandle = await window.showDirectoryPicker();`

Above line of code allowing me to select a directory & gives are reference to that chosen directory by using which I can iterate over each files & sun directory present in that selected directory.

I wanted to have a similar functionality with Html5 drag & drop i.e. when user drop a directory it should return a reference to that dropped directory. 

**To Reproduce**

**Expected behavior**

**Screenshots**

**Comment by mihajlija** [comment] 2021-08-03 15:22
Hi @pradeeptakhatoi, this repository is for web.dev (the site) and issues are for filing bugs on the site. Since this is not a bug on the site, I'll close the issue.

There are other places to get debugging support for your projects, such as [stackoverflow](https://stackoverflow.com/), I suggest you post your question there.

**Closed by mihajlija** 2021-08-03 15:22 UTC
Labels: P2, bug
