### ISSUE TITLE
Lint for broken links

### ISSUE THREAD

**Issue by heyawhite** [GoogleChrome/web.dev#7189] opened 2022-01-18 15:51 UTC
**Is your feature request related to a problem? Please describe.**
Sometimes content is published and links are broken, either due to a pre-existing page being redirected, a small misspelling, a link to a test page, or other errors.

**Describe the solution you'd like**
A linter could catch one or all of the potential scenarios as to why a link is broken.

**Additional context**
Suggested in https://github.com/GoogleChrome/web.dev/issues/7171

**Comment by rachelandrew** [comment] 2022-01-24 14:33
This looks like a duplicate of #1332

**Comment by heyawhite** [comment] 2022-01-26 19:39
Oh hey, look at that. Unsurprising that it's been brought up already. Doesn't look like there was movement yet.

I presume best practice would be to close this and ask follow up in #1332? If so, I'll do so.

**Comment by devnook** [comment] 2022-02-08 06:29
Duplicate of #1332

**Closed by devnook** 2022-02-08 06:29 UTC
Labels: feature request, P2, eng
