### ISSUE TITLE
Landing Screen View on 13.3" Laptops

### ISSUE THREAD

**Issue by una** [GoogleChrome/web.dev#4276] opened 2020-11-20 16:54 UTC
On a 13.3-inch screen, (2560 x 1600), the title of the articles gets cut off. This leaves the first view to mostly be the hero image when a notification banner is present, with no article context or information.

![Screen Shot 2020-11-20 at 11 44 33 AM](https://user-images.githubusercontent.com/1693164/99826993-13bffc00-2b27-11eb-8934-78d3ce5d5b97.png)

**Comment by robdodson** [comment] 2021-01-21 21:44
@una what do you think of a treatment similar to what we do on d.c.c.
https://developer.chrome.com/blog/timer-throttling-in-chrome-88/

**Comment by robdodson** [comment] 2021-04-06 03:30
I'm thinking we should at least match the hero style from d.c.c. because it looks nicer on larger displays. The one on web.dev cuts off abruptly when the screen is too big.

**Comment by robdodson** [comment] 2021-06-18 19:46
Closing as a dupe of #5540

**Closed by robdodson** 2021-06-18 19:46 UTC
Labels: P2, accepted, bug
