### ISSUE TITLE
Learn section hero images and cards have an extra white background

### ISSUE THREAD

**Issue by robdodson** [GoogleChrome/web.dev#7363] opened 2022-02-15 19:45 UTC
**Describe the bug**
A page like https://web.dev/learn-web-vitals/ displays a hero image to the right. This image seems to have an unintentional white background that's being added with CSS.

![image](https://user-images.githubusercontent.com/1066253/154136597-face3cec-d309-46ae-b6ce-9d71a65005d5.png)

The selector is:

```css
img[src$=".svg"], img[src$=".png"] {
    background-color: var(--color-transparent-img-mask);
}
```

But that seems maybe overly aggressive(?) because it gives a white background to every SVG on the site. It also appears when you hover the cards on the /learn page.

<img width="907" alt="image" src="https://user-images.githubusercontent.com/1066253/154136891-7205fe8c-1910-4435-b0fa-554aaddea9f1.png">

**Expected behavior**
The SVGs would have a transparent background. Here's the same page with the selector removed:

<img width="1428" alt="image" src="https://user-images.githubusercontent.com/1066253/154137063-ecc4ec0f-5ce3-47b6-b119-c5774cc845ec.png">

**Comment by jeffposnick** [comment] 2022-02-15 20:08
Lookin at https://github.com/GoogleChrome/web.dev/pull/6975, I believe this has to do with changes implemented in support of dark mode. Though arguably this specific example doesn't look ideal in dark mode, either:

<img width="375" alt="Screen Shot 2022-02-15 at 3 07 24 PM" src="https://user-images.githubusercontent.com/1749548/154140628-1b4d31bf-ae23-429d-b70d-baef639b1719.png">

Hopefully this is something that @hankchizljaw can look into as a follow-up of that earlier PR.

**Comment by hankchizljaw** [comment] 2022-02-16 09:44
The idea was that all of these illustrations need to be re-artworked because they were designed to only support light mode. Without any background, the black strokes disappear and it was always intended to be temporary.

I would definitely suggest looping in some design eyes to see how illustrations like this could be reworked to support multiple themes.

**Comment by robdodson** [comment] 2022-02-16 15:33
ah that makes sense, I didn't realize the dark mode had shipped yet. Looks nice!

As a short term fix, would it make sense to add the white background only when the user is in dark mode? Something like:

```css
[data-user-theme="dark"] img[src$=".svg"], img[src$=".png"] {
    background-color: var(--color-transparent-img-mask);
}
```

**Comment by hankchizljaw** [comment] 2022-02-16 18:46
Yeh `--color-transparent-img-mask` is [defined at the theme level](https://github.com/GoogleChrome/web.dev/blob/main/src/site/_data/design/themes.js#L187) and is currently set to `light-bright` which is white. A good fix would be to maybe [add a transparent value for the colour design tokens](https://github.com/GoogleChrome/web.dev/blob/main/src/site/_data/design/tokens.json#L150) and use that instead.

**Comment by rakshitgondwal** [comment] 2022-08-21 22:40
Is this issue still open?

**Comment by tomayac** [comment] 2022-08-22 07:34
The issue is definitely [still present on author pages](https://github.com/GoogleChrome/web.dev/issues/7363#issuecomment-1081560821).

**Comment by rakshitgondwal** [comment] 2022-08-22 17:18
Hey @tomayac 
Thanks a lot for the response!
Actually I was thinking that wouldn't by removing the background using photoshop and then replacing the old image with the new one solve this issue?

**Comment by tomayac** [comment] 2022-08-23 09:54
The [original comment](https://github.com/GoogleChrome/web.dev/issues/7363#issue-1139143680) describes the issue: an overly aggressive selector that applies a background color to all SVGs.

**Comment by mamieorine** [comment] 2023-03-30 11:26
The solution for this would involve recreating a dark-mode version of each image.

@tokyodanj will work on recreating the set of illustrations in support of dark mode.

**Comment by tokyodanj** [comment] 2023-03-31 11:29
@matthiasrohmer would you like us to recreate dark-mode versions of all the artwork in the next sprint?

**Comment by tokyodanj** [comment] 2023-04-11 15:12
Matthias would like us to create the dark-mode specific artwork as soon as we have capacity. To be confirmed if this will be possible in the latest sprint.

**Comment by tokyodanj** [comment] 2023-04-14 11:16
Dark-mode artwork created - ready for review before adding to site.

**Comment by dstmarthe** [comment] 2023-09-02 22:41
Thanks for raising this. We are moving to a new platform so the UI will be different in many parts. I can already confirm that the Collection pages and specifically this Core Web Vitals page will not have this problem. So, closing this as it will not be an issue after the move and content on this site is now frozen.

**Closed by dstmarthe** 2023-09-02 22:41 UTC
Labels: P2, accepted, eng - UI
