### ISSUE TITLE
Native lazy-loading on the web (loading attribute)

### ISSUE THREAD

**Issue by addyosmani** [GoogleChrome/web.dev#1045] opened 2019-06-26 20:06 UTC
**Describe the article you'd like to see**
What topics should it cover? Who is the intended audience?

We have an article on native lazy-loading that has been drafted in https://github.com/GoogleChrome/web.dev/pull/1016 with input from eng and product. We're still attempting to nail down whether we can finch lazy-loading into M76 or whether M77 is the earliest rollout for the feature. It will probably take a week or so to finalize this, but aiming to publish in July seems like a good target.

**Publish date**
When would you like to see this article go live? Is this a hard deadline?
Aim for < July 15th.

---

If you plan to write the article yourself be sure to read through [our wiki](https://github.com/googlechrome/web.dev/wiki) which explains how to add a new post to the site.

**Comment by robdodson** [comment] 2019-07-18 02:57
I think this is a dupe of #1059

**Closed by robdodson** 2019-07-18 02:57 UTC
Labels: content proposal, fast, p0
