### ISSUE TITLE
Add better disclosure widget.

### ISSUE THREAD

**Issue by robdodson** [GoogleChrome/web.dev#1269] opened 2019-08-06 02:14 UTC
**Is your feature request related to a problem? Please describe.**
In the writer's handbook and in some guides we often times have big chunks of information which are interesting but not critical for the reader. We should beef up our disclosure widget so we can show a nice abbreviated version of this information.

**Describe the solution you'd like**
Something like:
https://material.io/design/communication/writing.html#principles

cc @mfriesenhahn

**Comment by mfriesenhahn** [comment] 2019-08-06 15:35
Thanks, @robdodson!

**Comment by mfriesenhahn** [comment] 2019-10-09 00:37
Closing because this is a duplicate of #1454

**Closed by mfriesenhahn** 2019-10-09 00:37 UTC
Labels: feature request
