### ISSUE TITLE
Measure - Unable to get property '2' of undefined or null reference 

### ISSUE THREAD

**Issue by stewartwarner** [GoogleChrome/web.dev#516] opened 2018-12-07 18:24 UTC
Need better error messaging for some site errors still.  I'm sure other URL have encountered the undefined error message before.

URL:
- https://web.dev/measure

Browser:
- Win10 Edge
- Mac10.13.6 Chrome

Steps:

1. Go to the Measure page
2. Enter a URL (example www.teamlopro.com) and run audit
3. Notice the error Unable to get property '2' of undefined or null reference

Screenshot
![image](https://user-images.githubusercontent.com/2489799/49665549-142e5d80-fa0a-11e8-8db7-d90ec21112bb.png)

**Comment by ebidel** [comment] 2018-12-14 17:54
I'm not able to repro this using "http://www.teamlopro.com/".

**Comment by robdodson** [comment] 2018-12-14 21:11
assigning back to @stewartwarner to verify

**Comment by TimvdLippe** [comment] 2019-01-08 12:20
I am also unable to reproduce this error. Therefore, I am closing this issue.

**Closed by TimvdLippe** 2019-01-08 12:20 UTC
Labels: measure, p2
